version: '1'

services:
  express_app:
    container_name: node_spreads
    build:
      context: ./expressServer
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - vps2DockerNet
    depends_on:
      - redis
    restart: always
  meta_api:
    build:
      context: ./metaApiServer
    environment:
      - TOKEN=${TOKEN}
      - ACCOUNT_ID=${ACCOUNT_ID}
      - REDIS_URL=redis://redis:6379
    networks:
      - vps2DockerNet
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    networks:
      - vps2DockerNet
networks:
  vps2DockerNet:
    external: true